### PR TITLE
To ensure a master per zone with multi-AZ terraform deployments

### PR DESCRIPTION
**Pull request by baba230896**
- To ensure a master per zone with multi-AZ terraform deployments

Original bug is described at https://github.com/yugabyte/yugabyte-db/issues/4452

### CODE REVIEW

**Comment by iSignal** [comment]
Will take a look. Meanwhile could you also run shellcheck https://www.shellcheck.net/ on this script to catch any bash issues?

**Comment by baba230896** [comment]
I'll make the required changes and will follow [google bash style guide](https://google.github.io/styleguide/shellguide.html) as standard.

**Comment by iSignal** [comment]
Looks good, can you also add a test plan to describe what scenarios were tested?

**Comment by baba230896** [comment]
> Looks good, can you also add a test plan to describe what scenarios were tested?

Sure, I'll add.

**Review by iSignal — APPROVED** [review]
Looks like you've already tested this comprehensively. Please add the test plan details and merge it in.

**Comment by baba230896** [comment]
These below-mentioned scenarios are tested with these changes-

1. Tested: 3 nodes cluster with 3 YB masters on GCP, AZURE, and AWS using terraform.
2. Tested: 5 nodes cluster with 3 YB masters on GCP, AZURE, and AWS using terraform.
3. Tested: 7 nodes cluster with 5 YB masters on GCP, AZURE, and AWS using terraform.
4. Tested: With the help of [terraform-aws-yugabyte](https://github.com/yugabyte/terraform-aws-yugabyte) repo repetitive zones scenario ([A master per zone is not guaranteed with multi-AZ terraform deployments](https://github.com/yugabyte/yugabyte-db/issues/4452)) can be reproduced by providing repetitive zones and their respective subnets in main.tf for this [issue](https://github.com/yugabyte/yugabyte-db/issues/4452). Like this -

```
availability_zones = ["ap-southeast-2c", "ap-southeast-2c", "ap-southeast-2a", "ap-southeast-2a","ap-southeast-2b","ap-southeast-2b"]
subnet_ids = ["subnet-for-2c", "subnet-for-2c", "subnet-for-2a", "subnet-for-2a", "subnet-for-2b", "subnet-for-2b"]
```
```
availability_zones = ["ca-central-1b", "ca-central-1b", "ca-central-1b", "ca-central-1a", "ca-central-1a"]
subnet_ids = ["subnet-for-1b", "subnet-for-1b", "subnet-for-1b", "subnet-for-1a", "subnet-for-1a"]
```

**Pull request merged**
